#!/bin/sh
# This script is executed once after the module is installed by JeVois if it was added to the jevois/packages/ directory
# of the microSD card as a .jvpkg file. The script is deleted from the microSD card after execution.
#
# The caller script will set the current directory to the location of this script before launching the script.

# Add our video mappings to the main mappings file:
cat videomappings.cfg >> /jevois/config/videomappings.cfg

# Example of a simple message:
echo "SampleModule is now installed"

